#ifndef DEFS_H
#define DEFS_H

#define ERROR_LENGTH_LIMIT 1024
#define LOG_MSG_LENGTH_LIMIT 1024
#define INITIAL_FIELDS_COUNT 10
#define GOODS_FILE_SEPARATOR '|'
#define DEFAULT_FIELD_SIZE 20

#endif
